CREATE TABLE IF NOT EXISTS post
(
	id TEXT PRIMARY KEY NOT NULL,
	uri TEXT NOT NULL,
	user_id TEXT NOT NULL,
	content TEXT NOT NULL,
	created_at TEXT NOT NULL,

	FOREIGN KEY(user_id) REFERENCES user(id)
);
